[package]
name = "basti-common"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono = { workspace = true, features = ["serde"] }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
