[package]
name = "basti-daemon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bastid"
path = "src/main.rs"

[dependencies]
axum.workspace = true
basti-common = { path = "../basti-common" }
clap.workspace = true
etcd-client.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
