[package]
name = "basti-daemon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bastid"
path = "src/main.rs"

[dependencies]
axum = { workspace = true, features = ["http2"] }
basti-common = { path = "../basti-common" }
clap = { workspace = true }
etcd-client = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
