[package]
name = "basti-daemon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bastid"
path = "src/main.rs"

[dependencies]
clap = "4.5.1"
etcd = { version = "0.9.0", default-features = false }
hyper = { version = "1.2.0", features = ["http2", "server"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
