#!/usr/bin/env -S docker compose -p basti-gateway -f

services:
  haproxy:
    image: docker.io/haproxy:2.9-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 1337:1337