[package]
name = "basti-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "bastictl"
path = "src/main.rs"

[dependencies]
clap = "4.5.1"
reqwest = { version = "0.11.24", default-features = false }
serde_json = "1.0.114"
