#!/usr/bin/env -S docker -H ssh://pi@192.168.0.23 compose -p basti -f

volumes:
  etcd:
    name: basti-etcd

networks:
  default:
    name: basti

services:
  etcd:
    image: ghcr.io/satoqz/etcd:latest
    container_name: basti-etcd
    restart: unless-stopped
    ports:
      - 43278:43278
      - 54389:54389
    volumes:
      - etcd:/data
    command:
      - --name=pi-3
      - --data-dir=/data
      - --listen-client-urls=http://0.0.0.0:43278
      - --listen-peer-urls=http://0.0.0.0:54389
      - --advertise-client-urls=http://192.168.0.23:43278
      - --initial-advertise-peer-urls=http://192.168.0.23:54389
      - --initial-cluster=pi-1=http://192.168.0.21:54389,pi-2=http://192.168.0.22:54389,pi-3=http://192.168.0.23:54389
      - --initial-cluster-token=basti-etcd-cluster
      - --initial-cluster-state=new

  bastid:
    image: ghcr.io/satoqz/bastid:latest
    container_name: basti-bastid
    restart: unless-stopped
    ports:
      - 1337:1337
    depends_on:
      - etcd
    command:
      - --name=pi-3
      - --workers=1
      - --etcd=http://192.168.0.23:43278
