[package]
name = "basti-task"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
strum = "0.26.1"
strum_macros = "0.26.1"
uuid.workspace = true
