[package]
name = "basti-task"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
uuid = { version = "1.7.0", features = ["serde", "v4", "fast-rng"] }
